### ISSUE TITLE
Broked

### ISSUE THREAD

**Issue by c-brenn** [jameseggers/tcd-calendar#2]
send help

``` bash
Traceback (most recent call last):
  File "calendar_importer.py", line 121, in <module>
    importer.getAuthInfo()
  File "calendar_importer.py", line 23, in getAuthInfo
    self.__getMyTcdCalendar()
  File "calendar_importer.py", line 63, in __getMyTcdCalendar
    self.__createAppointmentsOnGoogleCal()
  File "calendar_importer.py", line 66, in __createAppointmentsOnGoogleCal
    self.__getGoogleAuthToken()
  File "calendar_importer.py", line 112, in __getGoogleAuthToken
    self.__GOOGLE_AUTH_TOKEN = req.text.split("Auth=")[1].replace("\n", "")
IndexError: list index out of range
```

**Comment by c-brenn** [comment]
time heals all wounds

**Comment by jameseggers** [comment]
@c-brenn http://tcal.me
